CREATE TABLE PERSON (ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, NAME VARCHAR(255), PASSWORD VARCHAR(255), COUNTRY INTEGER );
CREATE TABLE COUNTRY (ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, NAME VARCHAR(255));
CREATE TABLE RELATION (ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, FRIEND1 INTEGER, FRIEND2 INTEGER);
ALTER TABLE PERSON ADD CONSTRAINT FK_PERSON_COUNTRY FOREIGN KEY (COUNTRY) REFERENCES COUNTRY (ID);
ALTER TABLE RELATION ADD CONSTRAINT RELATION_FRIEND1 FOREIGN KEY (FRIEND1) REFERENCES PERSON (ID);
ALTER TABLE RELATION ADD CONSTRAINT RELATION_FRIEND2 FOREIGN KEY (FRIEND2) REFERENCES PERSON (ID);
